---

tasks:
- repo_path: https://github.com/apoydence/triple-c
  parameters:
    CF_SYSTEM_DOMAIN: ((CF_SYSTEM_DOMAIN))
    CF_USERNAME: ((CF_USERNAME))
    CF_PASSWORD: ((CF_PASSWORD))
    CF_SPACE: ((CF_SPACE))
    CF_ORG: ((CF_ORG))
    CF_APP_NAME: ((CF_APP_NAME))
  command: |
    set -ex

    echo "hi 4"
